<?php $menuSeat = true; ?>
{include file="common:header" /}
<link rel="stylesheet" href="__STATIC__/home/css/aui.css">
<link rel="stylesheet" href="__STATIC__/home/css/cart.css?v<?php echo time() ?>"">
<link rel="stylesheet" href="__STATIC__/home/css/classify.css?v<?php echo time() ?>">
<style>
    html,body{height: 100%;max-width: 640px;margin:0 auto;}
    h1 {
        margin-top: 12px;
    }
    .btn {
        padding-top: 10px;
    }
    .aui-bar-nav{border:none;background: #f5f5f5;}
    .main{height: calc(100% - 4.5rem);}

    #tab1-con1,#tab1-con2,#tab1-con3{height: 100%;}
    .aui-tab{border-bottom: solid 1px #eee;background: #fff;height: 42px;}
    .aui-tab-item{color: #666;width: 25%; height: 36px; line-height: 36px}
    .aui-tab-item.aui-active{border:none;color: #000;position: relative;}
    .aui-tab-item.aui-active:after{position: absolute;left: 40%;width: 20%;height: 2px;background: #00ae66;content: '';bottom:0;}
    .zyw-container.content, .zyw-container.content .con {
        height: 100%;
    }
    .zyw-container.content * {
        font-size: 16px!important;
    }
    .settle_box .total_amount dt p {
        font-size: 16px;
    }
    .settle_box .total_amount dd {
        font-size: 14px;
    }
    #total_price {
        width: 200px;
    }
    .settle_box .all_check {
        margin-top: 0px;
    }
    .settle_box .settle_btn {
        line-height: 26px;
    }
    .settle_box .total_amount dt span {
        color: #f34347;
        font-size: 16px;
        line-height: 20px;
    }
    .main .tab-con {
        display: block;
        left: 25%;
    }
</style>
<header class="zyw-header">
    <div class="zyw-container white-color">
        <div class="head-l"><a href="javascript:window.history.back(-1)" target="_self"><img src="__STATIC__/home/img/svg/head-return.svg" alt=""></a></div>
        <h1>共乐社区店 - 菜单</h1>
    </div>
</header>
<footer class="zyw-footer">
    <div class="zyw-container white-bgcolor">
        <div class="settle_box">
            <dl class="all_check select">
                <dt>
                    <div class="count_num"><span id="totalcountshow">0</span></div>
                </dt>
            </dl>
            <dl class="total_amount">
                <dt>合计：
                    <span id="total_price">
                            ¥ <b id="totalpriceshow">0</b>
                        </span>
                </dt>
                <dd>免运费</dd>
            </dl>
            <a class="settle_btn" href="javascript:void(0);" onclick="do_confirm()" id="confirm_cart">确认</a>
        </div>
    </div>
</footer>
<section class="zyw-container content JP_seat">
    <div class="aui-tab" id="tab">
        <div class="aui-tab-item aui-active">全部</div>
        <div class="aui-tab-item">当前已点</div>
        <div class="aui-tab-item">团体已下单</div>
    </div>
    <div class="main">
        <div class="aui-item" id="tab1-con1">
            <div class="left-menu left">
                <ul>
                    <li><span>所有</span></li>
                    {foreach name="varietyList" item="v"}
                    <li><span>{$v.name}</span></li>
                    {/foreach}
                </ul>
            </div>
            <div class="con">
                <div class="right-con con-active" style="display: none;">
                    <ul id="item_all">
                        {foreach name='list' item='v'}
                        <li data-id="{$v.id}">
                            <div class="menu-img">
                                <img src="<?php echo sfimg($v['image'], 115, 115) ?>" orgimg="<?php echo sfimg($v['image'], null, 1440) ?>">
                                {if condition="$v.quantity eq 0"}
                                    <label class="JV_status">售罄</label>
                                {/if}
                            </div>
                            <div class="menu-txt">
                                <h4 class="accountName">{$v.name}</h4>
                                <p class="list1">月销量：{$v.quantity_sale}</p>
                                <p class="list2">
                                    <b>￥</b><b>{$v.price}</b>
                                </p>
                                <div class="btn JI_food" foodid="{$v.id}">
                                    <button class="minus"></button>
                                    <i max-val="{$v.quantity}">0</i>
                                    {if condition='$v.quantity gt 0'}
                                    <button class="add"></button>
                                    {/if}
                                    <i class="price">{$v.price}</i>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                {foreach name="varietyList" item="data"}
                <div class="right-con" style="display: none;">
                    <ul>
                        {foreach name='data.list' item='v'}
                        <li>
                            <div class="menu-img">
                                <img src="<?php echo sfimg($v['image'], 115, 115) ?>" orgimg="<?php echo sfimg($v['image'], null, 1440) ?>">
                                {if condition="$v.quantity eq 0"}
                                <label class="JV_status">售罄</label>
                                {/if}
                            </div>
                            <div class="menu-txt">
                                <h4 class="accountName">{$v.name}</h4>
                                <p class="list1">月销量：{$v.quantity}</p>
                                <p class="list2">
                                    <b>￥</b><b>{$v.price}</b>
                                </p>
                                <div class="btn">
                                    <button class="minus"></button>
                                    <i max-val="{$v.quantity}">0</i>
                                    {if condition='$v.quantity gt 0'}
                                    <button class="add"></button>
                                    {/if}
                                    <i class="price">{$v.price}</i>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                {/foreach}
            </div>
        </div>
        <div class="aui-item aui-hide" id="tab1-con2">
            <div class="left-menu">
                <ul>
                    <li><span>自己</span></li>
                </ul>
            </div>
            <div class="con">
                <div class="right-con con-active">
                    <ul class="has-ed">
                        {foreach name='list' item='v'}
                        <li>
                            <div class="menu-img"><img src="<?php echo sfimg($v['image'], 115, 115) ?>" orgimg="<?php echo sfimg($v['image'], null, 1440) ?>"></div>
                            <div class="menu-txt">
                                <h4 class="accountName">{$v.name}</h4>
                                <p class="list1">月销量：{$v.quantity}</p>
                                <p class="list2">
                                    <b>￥</b><b>{$v.price}</b>
                                </p>
                                <div class="btn">
                                    <button class="minus"></button>
                                    <i max-val="{$v.quantity}">0</i>
                                    {if condition='$v.quantity gt 0'}
                                    <button class="add"></button>
                                    {/if}
                                    <i class="price">{$v.price}</i>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
        </div>
        <div class="aui-item aui-hide" id="tab1-con3">
            <div class="left-menu">
                <ul>
                    <li><span>所有</span></li>
                    <?php
                    $groupFoodList = array_merge($groupFoodList);
                    ?>
                    {foreach name="groupFoodList" item="v"}
                    <li><span>{$v.name}</span></li>
                    {/foreach}
                </ul>
            </div>
            <div class="con">
                <div class="right-con con-active" style="display: none;">
                    <ul id="item_all">
                        {foreach name="groupFoodList" item="list"}
                        {foreach name='list.foodList' item='v'}
                        <li>
                            <div class="menu-img"><img src="<?php echo sfimg($v['image'], 115, 115) ?>" orgimg="<?php echo sfimg($v['image'], null, 1440) ?>"></div>
                            <div class="menu-txt">
                                <h4 class="accountName">{$v.food_name}</h4>
                                <p class="list2">
                                    <b>￥</b><b>{$v.price}</b>
                                </p>
                                <div class="btn">
                                    x <i style="display: inline-block">{$v.quantity}</i>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                        {/foreach}
                    </ul>
                </div>
                {foreach name="groupFoodList" item="list"}
                <div class="right-con" style="display: none;">
                    <ul class="has-ed">
                        {foreach name='list.foodList' item='v'}
                        <li>
                            <div class="menu-img"><img src="<?php echo sfimg($v['image'], 115, 115) ?>" orgimg="<?php echo sfimg($v['image'], null, 1440) ?>"></div>
                            <div class="menu-txt">
                                <h4 class="accountName">{$v.food_name}</h4>
                                <p class="list2">
                                    <b>￥</b><b>{$v.price}</b>
                                </p>
                                <div class="btn">
                                    x <i style="display: inline-block">{$v.quantity}</i>
                                </div>
                            </div>
                        </li>
                        {/foreach}
                    </ul>
                </div>
                {/foreach}
            </div>
        </div>
    </div>
</section>
<script type="text/html" id="bar_gallery">
    <div id="galleryImg" alt="图片详情" role="img" class="weui-gallery__img pinch-zoom" style="text-align: center">
    </div>
    <div class="weui-gallery__opr">
        <a role="button" aria-label="关闭" href="javascript:" onclick="$('#gallery').fadeOut(100)"
           class="weui-gallery__del">
            <i class="weui-icon-cancel weui-icon_gallery-cancel"></i>
        </a>
    </div>
</script>
<div style="display: none;" role="dialog" aria-labelledby="galleryImg" aria-hidden="true" aria-modal="true"
     class="weui-gallery" id="gallery" onclick="$('#gallery').fadeOut(100)">
</div>
<script type="text/javascript" src="__STATIC__/home/js/api.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/add.js__URL_CACHE__"></script>
<script type="text/javascript" src="__STATIC__/home/js/aui-tab.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/pinchzoom.js__URL_CACHE__" ></script>
<script type="text/javascript">
    apiready = function() {
        api.parseTapmode();
    }
    var tab = new auiTab({
        element: document.getElementById("tab"),

    }, function(ret) {
        if (ret) {
            //定义获取对象的所有兄弟节点的函数，
            function siblings(elm) {
                var a = [];
                var p = elm.parentNode.children;
                for (var i = 0, pl = p.length; i < pl; i++) {
                    if (p[i] !== elm) a.push(p[i]);
                }
                return a;
            }
            var index = ret.index;
            var activeC = document.getElementById("tab1-con" + index);
            $(activeC).find('.left-menu li').first().click();
            activeC.className = "";
            for (var i = 0; i < siblings(activeC).length; i++) {
                siblings(activeC)[i].className = "aui-hide";
            }
        }
    });
    $(function () {
        $('.menu-img img').click(function () {
            $('#gallery').html($('#bar_gallery').html());
            $('#galleryImg').html('<img src="' + $(this).attr('orgimg') + '" style="max-height: 100%; display: none" />');
            $('#gallery').fadeIn(100, 'swing', function () {
                $('div.pinch-zoom').each(function () {
                    new RTP.PinchZoom($(this), {});
                });
            });
        });
        {notempty name="indentFoodList"}
            {foreach name="indentFoodList" item="v"}
            $('.JI_food[foodid="{$v.food_id}"] .add').each(function () {
                for (let i = 1; i <= {$v.quantity}; i++) {
                    $(this).click();
                }
            });
            {/foreach}
        {/notempty}
    });
    function do_confirm() {
        let param = {ids:[], qtys:[], group_id: <?php echo $groupId ?>};
        $('#item_all li').each(function () {
            let qty = parseInt($(this).find('i').html());
            if (qty > 0) {
                let id = $(this).attr('data-id');
                param.ids.push(id);
                param.qtys.push(qty);
            }
        });
        if (param.ids.length > 0) {
            $.showLoading('正在提交');
            $.post('<?php echo sfurl("/seat/group/saveIndent") ?>', param, function (ret) {
               ret = eval('(' + ret + ')');
                $.hideLoading();
               if (ret.code == 1) {
                   $.toast("下单成功", '', function () {
                       $.showLoading('前往订单');
                       window.location.href = "<?php echo sfurl('/indent/order/show/status/W') ?>";
                   });
               } else {
                   $.toast(ret.msg, "cancel");
               }
            });
        }
    }
</script>
{include file="common:footer" /}