{include file="common:header" /}
<link rel="stylesheet" href="__STATIC__/home/css/find.css">
<header class="zyw-header">
    <div class="zyw-container white-color">
        <div class="head-l"><a href="javascript:window.history.back(-1)" target="_self"><img src="__STATIC__/home/img/svg/head-return.svg" alt=""></a></div>
        <h1>团体点餐</h1>
        <div class="head-r"></div>
    </div>
</header>
<section class="zyw-container">
    <div class="find-group1">
        <div class="find-group1-item mb-625 white-bgcolor">
            <div class="group1-hd clearfix mb-625">
                <div class="pull-left hd-img"><img src="__STATIC__/home/img/user4.png" alt=""></div>
                <div class="pull-left">
                    <p class="hd-name">南山区卓越前海壹号T3写字楼</p>
                    <span class="hd-time">2023-04-20</span>
                </div>
                <a href="" class="pull-right hd-take">+ 进入点餐</a>
            </div>
            <div class="group1-bd clearfix">
                <div class="pull-left bd-l">
                    <div class="bd-img"><img src="https://img10.360buyimg.com/n4/jfs/t19768/164/187787594/229738/a7cbf352/5a6296c9Nf984db1f.jpg" alt=""></div>
                </div>
                <div class="pull-right bd-r">
                    <h4 class="bd-title">
                        <ul>
                            <li>香煎鱼腩饭 x 3</li>
                            <li>砂锅猪脚饭 x 2</li>
                            <li>可乐鸭饭 x 2</li>
                            <li>辣子鸡饭 x 1</li>
                        </ul>
                    </h4>
                </div>
                <span class="bd-intro">2公里</span>
            </div>
        </div>
    </div>
</section>
{include file="common:footer" /}