<?php
$module = strtolower(\think\facade\Request::module());
$controller = strtolower(\think\facade\Request::controller());
$action = strtolower(\think\facade\Request::action());
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>[title] - <?php echo \app\base\model\Setting::instance()->getValue('site_name') ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>
<body ontouchstart>