<?php $menuAll = true; ?>
{include file="common:admin_header" /}
<link rel="stylesheet" href="__STATIC__/home/css/aui.css">
<link rel="stylesheet" href="__STATIC__/home/css/cart.css__URL_CACHE__">
<link rel="stylesheet" href="__STATIC__/home/css/classify.css__URL_CACHE__">
<style>
    html,body{height: 100%;max-width: 640px;margin:0 auto;}
    h1 {
        margin-top: 12px;
    }
    .btn {
        padding-top: 10px;
    }
    .aui-bar-nav{border:none;background: #f5f5f5;}
    .main{height: calc(100% - 4.5rem);}

    #tab1-con1,#tab1-con2,#tab1-con3{height: 100%;}
    .aui-tab{border-bottom: solid 1px #eee;background: #fff;height: 42px;}
    .aui-tab-item{color: #666;width: 25%; height: 36px; line-height: 36px}
    .aui-tab-item.aui-active{border:none;color: #000;position: relative;}
    .aui-tab-item.aui-active:after{position: absolute;left: 40%;width: 20%;height: 2px;background: #00ae66;content: '';bottom:0;}
    .zyw-container.content, .zyw-container.content .con {
        height: 100%;
    }
    .zyw-container.content * {
        font-size: 16px!important;
    }
    .zyw-container.content .right-con * {
        font-size: 14px!important;
    }
    .weui-label {
        margin: 0;
        width: 86px;
    }
    input.weui-input {
        border: 1px solid #ccc;
        padding: 0 5px;
    }
    .weui-cells__tips {
        text-align: right;
        margin: -10px 0 0;
    }

    .settle_box .total_amount dt p {
        font-size: 16px;
    }
    .settle_box .total_amount dd {
        font-size: 14px;
    }
    #total_price {
        width: 200px;
    }
    .settle_box .all_check {
        margin-top: 0px;
    }
    .settle_box .settle_btn {
        line-height: 26px;
    }
    .settle_box .total_amount dt span {
        color: #f34347;
        font-size: 16px;
        line-height: 20px;
    }
    .main .tab-con {
        display: block;
        left: 25%;
    }
    .weui-cell_select {
        padding: 10px 15px;
    }
</style>
<header class="zyw-header">
    <div class="zyw-container white-color">
        <div class="head-l"><a href="javascript:window.history.back(-1)" target="_self"><img src="__STATIC__/home/img/svg/head-return.svg" alt=""></a></div>
        <h1>店铺设置</h1>
    </div>
</header>
<section class="zyw-container content JP_seat">
    <div class="main">
        <div class="left-menu left">
            <ul>
                <li{if condition="$group eq 'default'"} class="active" isActive="1"{/if}><a class="j-sfloading" href="<?php echo sfurl('/base/admin/setting'); ?>"><span>基础</span></a></li>
                <?php
                foreach ($groupList as $value) :
                    if ($value['code'] == 'default') {
                        continue;
                    }
                    ?>
                    <li{if condition="$group eq $value.code"} class="active" isActive="1"{/if}><a class="j-sfloading" href="<?php echo sfurl('/base/admin/setting/group/' . $value['code']); ?>"><span><?php echo $value['code']; ?></span></a></li>
                <?php
                endforeach;
                ?>
            </ul>
        </div>
        <div class="con">
            <div class="right-con con-active" style="display: none;">
                <form id="frm_main" method="post" onsubmit="return sfsubmiting(check_change)">
                    <input type="hidden" name="site" value="<?php echo sfret('site', 0); ?>">
                    <input type="hidden" name="group" value="<?php echo sfret('group', 'default'); ?>">
                    {foreach name='list' item='value'}
                    <div class="weui-cell{if condition="$value.format eq 'select'"} weui-cell_select{/if}">
                        <div class="weui-cell__hd"><label class="weui-label"{if condition="$value.format eq 'checkbox'"} style="margin-top: -11px"{/if}>{$value.name}</label></div>
                        <div class="weui-cell__bd">
                            {include file="base:admin:format" /}
                        </div>
                    </div>
                    <div class="weui-cells__tips">&nbsp;{$value.note}</div>
                    {/foreach}
                </form>
            </div>
        </div>
    </div>
</section>
<script type="text/html" id="bar_gallery">
    <div id="galleryImg" alt="图片详情" role="img" class="weui-gallery__img pinch-zoom" style="text-align: center">
    </div>
    <div class="weui-gallery__opr">
        <a role="button" aria-label="关闭" href="javascript:" onclick="$('#gallery').fadeOut(100)"
           class="weui-gallery__del">
            <i class="weui-icon-cancel weui-icon_gallery-cancel"></i>
        </a>
    </div>
</script>
<div style="display: none;" role="dialog" aria-labelledby="galleryImg" aria-hidden="true" aria-modal="true"
     class="weui-gallery" id="gallery" onclick="$('#gallery').fadeOut(100)">
</div>
<script type="text/javascript" src="__STATIC__/home/js/api.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/add.js__URL_CACHE__"></script>
<script type="text/javascript" src="__STATIC__/home/js/aui-tab.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/pinchzoom.js__URL_CACHE__" ></script>
<script type="text/javascript">
    window.leftMenuNotAuto = true;
    apiready = function() {
        api.parseTapmode();
    }
    var tab = new auiTab({
        element: document.getElementById("tab"),

    }, function(ret) {
        if (ret) {
            //定义获取对象的所有兄弟节点的函数，
            function siblings(elm) {
                var a = [];
                var p = elm.parentNode.children;
                for (var i = 0, pl = p.length; i < pl; i++) {
                    if (p[i] !== elm) a.push(p[i]);
                }
                return a;
            }
            var index = ret.index;
            var activeC = document.getElementById("tab1-con" + index);
            $(activeC).find('.left-menu li').first().click();
            activeC.className = "";
            for (var i = 0; i < siblings(activeC).length; i++) {
                siblings(activeC)[i].className = "aui-hide";
            }
        }
    });
    $(function () {
        $('.menu-img img').click(function () {
            $('#gallery').html($('#bar_gallery').html());
            $('#galleryImg').html('<img src="' + $(this).attr('orgimg') + '" style="max-height: 100%; display: none" />');
            $('#gallery').fadeIn(100, 'swing', function () {
                $('div.pinch-zoom').each(function () {
                    new RTP.PinchZoom($(this), {});
                });
            });
        });
     });
</script>
{include file="common:footer" /}