<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{$title} - <?php echo \app\base\model\Setting::instance()->getValue('site_name') ?>后台</title>
    <meta name="Keywords" content="<?php echo \app\base\model\Setting::instance()->getValue('site_keywords') ?>" />
    <meta name="Description" content="<?php echo \app\base\model\Setting::instance()->getValue('site_description') ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="icon" href="data:image/ico;base64,aWNv">
    <link rel="stylesheet" href="__STATIC__/home/css/weui.min.css">
    <link rel="stylesheet" href="__STATIC__/home/css/jquery-weui.min.css">
    <link href="__STATIC__/home/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="__STATIC__/home/css/font-awesome.min.css">
    <link rel="stylesheet" href="__STATIC__/home/css/main.css?v<?php echo time() ?>">
    <link rel="stylesheet" href="__STATIC__/home/css/home.css">
    <link rel="stylesheet" href="__STATIC__/home/css/theme-color.css">
    <!--[if lt IE 9]>
    <script src="__STATIC__/home/js/html5shiv.js"></script>
    <script src="__STATIC__/home/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<footer class="zyw-footer">
    <div class="zyw-container white-bgcolor">
        <div class="weui-tabbar">
            <a href="<?php echo sfurl('/admin') ?>" class="weui-tabbar__item weui-bar__item--on">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-1-1.svg" alt="">
                </div>
                <p class="weui-tabbar__label">全部功能</p>
            </a>
            <a href="class.php" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-2.svg" alt="">
                </div>
                <p class="weui-tabbar__label">菜单管理</p>
            </a>
            <a href="find.html" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-3.svg" alt="">
                </div>
                <p class="weui-tabbar__label">宝贝管理</p>
            </a>
            <a href="home.html" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
                </div>
                <p class="weui-tabbar__label">财务中心</p>
            </a>
        </div>
    </div>
</footer>