<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{$title} - <?php echo \app\base\model\Setting::instance()->getValue('site_name') ?></title>
    <meta name="Keywords" content="<?php echo \app\base\model\Setting::instance()->getValue('site_keywords') ?>" />
    <meta name="Description" content="<?php echo \app\base\model\Setting::instance()->getValue('site_description') ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="icon" href="data:image/ico;base64,aWNv">
    <link rel="stylesheet" href="__STATIC__/home/css/weui.min.css">
    <link rel="stylesheet" href="__STATIC__/home/css/jquery-weui.min.css">
    <link href="__STATIC__/home/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="__STATIC__/home/css/font-awesome.min.css">
    <link rel="stylesheet" href="__STATIC__/home/css/main.css?v<?php echo time() ?>">
    <link rel="stylesheet" href="__STATIC__/home/css/index.css?v<?php echo time() ?>">
    <link rel="stylesheet" href="__STATIC__/home/css/theme-color.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<footer class="zyw-footer">
    <div class="zyw-container white-bgcolor clearfix">
        <div class="weui-tabbar">
            <a href="index.php" class="weui-tabbar__item weui-bar__item--on">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-1-1.svg" alt="">
                </div>
                <p class="weui-tabbar__label">首页</p>
            </a>
            <a href="seat" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-2.svg" alt="">
                </div>
                <p class="weui-tabbar__label">点餐</p>
            </a>
            <a href="category" class="weui-tabbar__item">
                <span class="weui-badge" style="position: absolute;top: -.4em;right: 1em;">0</span>
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-3.svg" alt="">
                </div>
                <p class="weui-tabbar__label">商品</p>
            </a>
            <a href="member" class="weui-tabbar__item">
                <div class="weui-tabbar__icon">
                    <img src="__STATIC__/home/img/svg/foot-5.svg" alt="">
                </div>
                <p class="weui-tabbar__label">我的</p>
            </a>
        </div>
    </div>
</footer>