<?php $menuAll = true; ?>
{include file="common:admin_header" /}
<link rel="stylesheet" href="__STATIC__/home/css/aui.css">
<link rel="stylesheet" href="__STATIC__/home/css/cart.css__URL_CACHE__">
<link rel="stylesheet" href="__STATIC__/home/css/classify.css__URL_CACHE__">
<style>
    html,body{height: 100%;max-width: 640px;margin:0 auto;}
    h1 {
        margin-top: 12px;
    }
    .btn {
        padding-top: 10px;
    }
    .right-con li .btn {
        bottom: 28px;
        right: 5px;
        padding: 0;
        width: 86px;
        text-align: center;
    }
    .right-con li .btn a {
        color: rgb(179, 115, 253);
        text-decoration: underline!important;
    }
    .right-con li .menu-txt {
        width: 60%;
    }
    .weui-cell_swiped * {
        padding: 2px 0 1px;
        margin: 0;
    }
    .weui-cell_swiped span {
        line-height: 28px;
        padding-left: 1px;
        padding-right: 1px;
    }

    .main{height: calc(100% - 4.5rem);}

    #tab1-con1{padding-bottom: 3rem;}
    #tab1-con1,#tab1-con2,#tab1-con3{height: 100%;}
    .aui-tab{border-bottom: solid 1px #eee;background: #fff;height: 42px;}
    .aui-tab-item{color: #666;width: 25%; height: 36px; line-height: 36px}
    .aui-tab-item.aui-active{border:none;color: #000;position: relative;}
    .aui-tab-item.aui-active:after{position: absolute;left: 40%;width: 20%;height: 2px;background: #00ae66;content: '';bottom:0;}
    .zyw-container.content, .zyw-container.content .con {
        height: 100%;
    }
    .zyw-container.content * {
        font-size: 16px!important;
    }
    .settle_box .total_amount dt p {
        font-size: 16px;
    }
    .settle_box .total_amount dd {
        font-size: 14px;
    }
    .settle_box .total_amount dt span {
        color: #f34347;
        font-size: 16px;
        line-height: 20px;
    }
    .main .tab-con {
        display: block;
        left: 25%;
    }
    .toolbar .title {
        font-size: 14px;
        line-height: 1px;
    }
    .weui-grid {
        min-height: 102px;
    }
    .right-con li .menu-img {
        width: 186px;
    }
    .right-con li .menu-img img {
        width: 186px;
        height: 140px;
    }
</style>
<header class="zyw-header">
    <div class="zyw-container white-color">
        <div class="head-l"><a href="javascript:window.history.back(-1)" target="_self"><img src="__STATIC__/home/img/svg/head-return.svg" alt=""></a></div>
        <h1>广告列表</h1>
    </div>
</header>
<section class="zyw-container content JP_seat">
    <div class="main">
        <div class="left-menu left">
            <ul>
                <?php
                foreach ($moldList as $value) :
                    ?>
                    <li{if condition="$type eq $value.type"} class="active" isActive="1"{/if}><a class="j-sfloading" href="<?php echo sfurl('/ad/admin/index/type/' . $value['type']); ?>"><span><?php echo $value['name']; ?></span></a></li>
                <?php
                endforeach;
                ?>
            </ul>
        </div>
        <div class="con">
            <div class="right-con con-active" style="display: none;">
                <ul>
                    {foreach name='list' item='v'}
                    <li class="JP_food_{$v.id}">
                        <div class="menu-img"><a href="#"><img src="<?php echo sfimg($v['img'], 186, 140) ?>"></a></div>
                        <div class="menu-txt">
                            <div class="weui-cell weui-cell_swiped">
                                <div class="weui-cell__bd" style="transform: translate3d(0px, 0px, 0px);">
                                    <div class="weui-cell">
                                        <div class="weui-cell__bd">
                                            <a href="#"><p class="JV_name">{$v.title}</p></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="weui-cell__ft JP_status_operate">
                                    {if condition='$v.status eq "Y"'}
                                    <span class="weui-swiped-btn weui-swiped-btn_warn delete-swipeout" onclick="do_status_down({$v.id})">&nbsp;下架&nbsp;</span>
                                    {else/}
                                    <span class="weui-swiped-btn weui-swiped-btn_warn delete-swipeout" onclick="do_status_up({$v.id})">&nbsp;上架&nbsp;</span>
                                    {/if}
                                </div>
                            </div>
                            <p class="list1">点击数<b>{$v.value}</b></p>
                            <div class="btn">
                                <a href="javascript:;">编辑</a>
                            </div>
                        </div>
                    </li>
                    {/foreach}
                </ul>
            </div>
        </div>
    </div>
</section>
<script type="text/html" id="bar_gallery">
    <div id="galleryImg" alt="图片详情" role="img" class="weui-gallery__img pinch-zoom" style="text-align: center">
    </div>
    <div class="weui-gallery__opr">
        <a role="button" aria-label="关闭" href="javascript:" onclick="$('#gallery').fadeOut(100)"
           class="weui-gallery__del">
            <i class="weui-icon-cancel weui-icon_gallery-cancel"></i>
        </a>
    </div>
</script>
<div style="display: none;" role="dialog" aria-labelledby="galleryImg" aria-hidden="true" aria-modal="true"
     class="weui-gallery" id="gallery" onclick="$('#gallery').fadeOut(100)">
</div>
<script type="text/javascript" src="__STATIC__/home/js/api.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/add.js__URL_CACHE__"></script>
<script type="text/javascript" src="__STATIC__/home/js/aui-tab.js" ></script>
<script type="text/javascript" src="__STATIC__/home/js/pinchzoom.js__URL_CACHE__" ></script>
<script type="text/javascript">
    apiready = function() {
        api.parseTapmode();
    }
    var tab = new auiTab({
        element: document.getElementById("tab"),

    }, function(ret) {
        if (ret) {
            //定义获取对象的所有兄弟节点的函数，
            function siblings(elm) {
                var a = [];
                var p = elm.parentNode.children;
                for (var i = 0, pl = p.length; i < pl; i++) {
                    if (p[i] !== elm) a.push(p[i]);
                }
                return a;
            }
            var index = ret.index;
            var activeC = document.getElementById("tab1-con" + index);
            $(activeC).find('.left-menu li').first().click();
            activeC.className = "";
            for (var i = 0; i < siblings(activeC).length; i++) {
                siblings(activeC)[i].className = "aui-hide";
            }
        }
    });
</script>
{include file="common:footer" /}