<?php $menuHome = true; ?>
{include file="common:header" /}
<link rel="stylesheet" href="__STATIC__/home/css/index.css?v<?php echo time() ?>">
<link rel="stylesheet" href="__STATIC__/home/css/swiper.min.css">
<header class="zyw-header">
    <div class="zyw-container white-color">
        <div class="head-l"><i class="head-l-svg" aria-hidden="true"></i> 共乐社区店</div>
        <div class="head-search">
            <i class="fa fa-search" aria-hidden="true"></i>
            <input type="text" placeholder="输入要搜索的菜品或商品" class="white-color">
        </div>
        <div class="head-r"><a href="javascript:;" onclick="do_qrcode()"><i class="head-r-svg" aria-hidden="true"></i></a></div>
    </div>
</header>
<section class="zyw-container">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="https://img.alicdn.com/imgextra/i4/2590951958/TB2Fz6XfgMPMeJjy1XbXXcwxVXa_!!2590951958.jpg" alt=""></div>
            <div class="swiper-slide"><img src="https://img.alicdn.com/imgextra/i4/2590951958/TB2z.NKbaagSKJjy0FgXXcRqFXa_!!2590951958.jpg" alt=""></div>
            <div class="swiper-slide"><img src="https://img.alicdn.com/imgextra/i4/2590951958/TB2ZxVCbjihSKJjy0FeXXbJtpXa_!!2590951958.jpg" alt=""></div>
        </div>
        <!-- 如果需要分页器 -->
        <div class="swiper-pagination"></div>
    </div>
    <div class="index-class white-bgcolor">
        <div class="weui-flex">
            <div class="weui-flex__item">
                <a href="group">
                    <div class="index-class-img">
                        <img src="__STATIC__/home/img/sjtx.png" alt="">
                    </div>
                    <p class="index-class-text">团体点餐</p>
                </a>
            </div>
        </div>
    </div>
    <div class="index-news">
        <div class="news-cont white-bgcolor">
            <strong>最新<em>资讯</em>：</strong>
            <div class="infoBox">
                <ul class="swiper-wrapper">
                    <li class="swiper-slide"><a href="#"><span><i>热</i>点餐系统微信版上线啦！</span></a></li>
                    <li class="swiper-slide"><a href="#"><span>马上就要开始营业了，欢迎预订！</span></a></li>
                </ul>
            </div>
            <ul>
                <li><a href=""></a></li>
            </ul>
            <a href="" class="news-more">更多</a>
        </div>
    </div>
</section>
<script src="__STATIC__/home/js/swiper.min.js"></script>
<script type="text/javascript">
        function scan_qrcode()
        {
            wx.scanQRCode({
                needResult: 0, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
                scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
                success: function (res) {
                    var result = res.resultStr; // 当needResult 为 1 时，扫码返回的结果
                }
            });
        }
        // 轮播
        $(document).ready(function () {
            // 顶部轮播图
            var mySwiper = new Swiper ('.swiper-container', {
                // 如果需要分页器
                autoplay:true,
                pagination: {
                    el: '.swiper-pagination'
                }
            });
            // 秒杀商品滑动
            var swiper = new Swiper('.seckill-wares', {
                slidesPerView: 3.5,
                spaceBetween: 5,
                freeMode: true
            });
            // 新闻资讯
            var swiper2 = new Swiper('.infoBox', {
                autoplay:true,
                delay: 5000,
                direction: 'vertical'
            });
        });
</script>
{include file="common:footer" /}