{include file="common:header" /}
<link rel="stylesheet" href="__STATIC__/home/css/weui.min.css">
<link rel="stylesheet" href="__STATIC__/home/css/jquery-weui.min.css">
<link href="__STATIC__/home/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="__STATIC__/home/css/font-awesome.min.css">
<link rel="stylesheet" href="__STATIC__/home/css/main.css">
<link rel="stylesheet" href="__STATIC__/home/css/home.css">
<link rel="stylesheet" href="__STATIC__/home/css/theme-color.css">
<section class="zyw-container">
    <div class="home-head white-bgcolor clearfix">
        <div class="head-img">
            <div class="head-logo"><img src="__STATIC__/home/img/mylogo.png" alt=""></div>
            <div class="head-name">抓耗子的猫</div>
            <div class="head-name" style="right: 8px; left: auto"><a href="/admin">管理店铺</a></div>
            <div class="head-icon">
                <a href=""><img src="__STATIC__/home/img/svg/home-cog.svg" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-message.svg" alt=""></a>
            </div>
        </div>
        <div class="head-cont">
            <div class="weui-flex">
                <div class="weui-flex__item"><a href="star.html"><p>12</p><span>喜欢的菜品</span></a></div>
                <div class="weui-flex__item"><a href="star.html"><p>6</p><span>收藏的宝贝</span></a></div>
                <div class="weui-flex__item"><a href="star.html"><p>16</p><span>我的足迹</span></a></div>
            </div>
        </div>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="order.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 点餐订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                查看所有已点菜品
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">待付款</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待配送</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">待评价</p>
        </a>
        <a href="javascript:;" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
            </div>
            <p class="weui-flex__label">退款/售后</p>
        </a>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="order.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 商品订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                查看所有已购宝贝
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">待付款</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待发货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">待评价</p>
        </a>
        <a href="javascript:;" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
            </div>
            <p class="weui-flex__label">退款/售后</p>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-2.svg" alt=""> 积分</p>
            </div>
            <div class="weui-cell__ft choose-des">
                当前可用积分200
            </div>
        </a>
        <a class="weui-cell weui-cell_access" href="coupon.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-3.svg" alt=""> 优惠券</p>
            </div>
            <div class="weui-cell__ft choose-des">
                2张
            </div>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="javascript:;">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-4.svg" alt=""> 地址管理</p>
            </div>
            <div class="weui-cell__ft choose-des">
            </div>
        </a>
        <a class="weui-cell weui-cell_access" href="login.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-5.svg" alt=""> 意见反馈</p>
            </div>
            <div class="weui-cell__ft choose-des">
            </div>
        </a>
    </div>
</section>
<script src="__STATIC__/home/js/jquery.min.js"></script>
<script src="__STATIC__/home/js/jquery-weui.min.js"></script>
<script src="__STATIC__/home/js/bootstrap.min.js"></script>
{include file="common:footer" /}