<?php $menuMember = true; ?>
{include file="common:header" /}
<link rel="stylesheet" href="__STATIC__/home/css/home.css">
<section class="zyw-container">
    <div class="home-head white-bgcolor clearfix">
        <div class="head-img">
            <div class="head-logo"><img src="__STATIC__/home/img/mylogo.png" alt=""></div>
            <div class="head-name JU_name">-</div>
            <div class="head-name" style="right: 8px; left: auto"><a href="/admin">管理店铺</a></div>
            <div class="head-icon">
                <a href="javascript:;" onclick="update_name()"><img src="__STATIC__/home/img/svg/home-cog.svg" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-message.svg" alt=""></a>
            </div>
        </div>
        <div class="head-cont">
            <div class="weui-flex">
                <div class="weui-flex__item"><a href="javascript:;"><p>0</p><span>喜欢的菜品</span></a></div>
            </div>
        </div>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="<?php echo sfurl('/indent/order') ?>">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 外卖订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                查看所有外卖
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="<?php echo sfurl('/indent/order/show/status/W') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待配餐</p>
        </a>
        <a href="<?php echo sfurl('/indent/order/show/status/P') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="<?php echo sfurl('/indent/order/show/status/C') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">已收货</p>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="javascript:update_telephone();">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-4.svg" alt=""> 填补手机号</p>
            </div>
            <div class="weui-cell__ft choose-des" id="member_telephone">
                <?php echo sfdesensitize(app\base\model\Session::instance()->getTelephone(), 3, 4) ?>
            </div>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="#">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-5.svg" alt=""> 意见反馈</p>
            </div>
            <div class="weui-cell__ft choose-des">
            </div>
        </a>
    </div>
</section>
<script type="text/javascript">
    function update_telephone() {
        let memberTelephone = window.memberTelephone || '<?php echo app\base\model\Session::instance()->getTelephone() ?>';
        $.prompt({
            title: '请输入您的联系方式',
            text: '（手机或座机）',
            input: memberTelephone,
            empty: false,
            onOK: function (input) {
                if (sfvalidtelephone(input)) {
                    $.showLoading();
                    window.memberTelephone = input;
                    $.getJSON('<?php echo sfurl("/base/session/saveInfo") ?>', {telephone: window.memberTelephone}, function (ret) {
                        $.hideLoading();
                        if (ret.code == 1) {
                            window.memberTelephone = input;
                            $('#member_telephone').html(input);
                        } else {
                            $.toast(ret.msg, 'cancel');
                        }
                    });
                } else {
                    $.toptip('联系方式填写不正确！');
                }
            },
            onCancel: function () {
            }
        });
    }
    function update_name() {
        let memberName = '<?php echo app\base\model\Session::instance()->getName() ?>';
        $.prompt({
            title: '请输入您的昵称',
            text: '（2-6长度）',
            input: memberName,
            empty: false,
            onOK: function (input) {
                while(!input || input.toLowerCase() == 'null' || input.length == 0) {
                    read_member_name();
                }
                window.memberName = input;
                $.getJSON('<?php echo sfurl("/base/session/saveInfo") ?>', {name: window.memberName}, function (ret) {
                });
                if ($('.JU_name').length > 0) {
                    $('.JU_name').html(window.memberName);
                }
            },
            onCancel: function () {
                read_member_name();
            }
        });
    }
</script>
{include file="common:footer" /}