{include file="common:admin_header" /}
<style type="text/css">
    .home-head .head-img {
        height: 60px;
    }
</style>
<section class="zyw-container">
    <div class="home-head white-bgcolor clearfix">
        <div class="head-img">
            <div class="head-logo"><img src="__STATIC__/home/img/mylogo.png" alt=""></div>
            <div class="head-name">抓耗子的猫</div>
            <div class="head-icon">
                <a href="<?php echo sfurl('/') ?>"><img src="__STATIC__/home/img/svg/home.svg" height="24" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-cog.svg" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-message.svg" alt=""></a>
            </div>
        </div>
        <div class="head-cont">
            <div class="weui-flex">
                <div class="weui-flex__item"><a href="star.html"><p>12</p><span>今日外卖单</span></a></div>
                <div class="weui-flex__item"><a href="star.html"><p>6</p><span>今日快递单</span></a></div>
                <div class="weui-flex__item"><a href="star.html"><p>16</p><span>今日新增会员</span></a></div>
            </div>
        </div>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="order.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 外卖订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                查看所有外卖
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">待配餐</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待配送</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">待评价</p>
        </a>
        <a href="javascript:;" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
            </div>
            <p class="weui-flex__label">退款/售后</p>
        </a>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="order.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 快递订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                查看所有快递
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">待付款</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待发货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">待评价</p>
        </a>
        <a href="javascript:;" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
            </div>
            <p class="weui-flex__label">退款/售后</p>
        </a>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="order.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="img/svg/home-1.svg" alt=""> 其他功能</p>
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625" style="margin-bottom: 0">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">回复评价</p>
        </a>
        <a href="<?php echo sfurl('/admin/item/ad') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">广告管理</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">资讯管理</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">预约管理</p>
        </a>
        <a href="javascript:;" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-tk.svg" alt="">
            </div>
            <p class="weui-flex__label">会员列表</p>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">店铺管理</p>
        </a>
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">营销分析</p>
        </a>
        <a href="order.html" class="weui-flex__item">
        </a>
        <a href="order.html" class="weui-flex__item">
        </a>
        <a href="javascript:;" class="weui-flex__item">
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="coupon.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-3.svg" alt=""> 优惠券管理</p>
            </div>
            <div class="weui-cell__ft choose-des">
                共2张
            </div>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="login.html">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-3.svg" alt=""> 支持系统</p>
            </div>
            <div class="weui-cell__ft choose-des">
            </div>
        </a>
    </div>
</section>
{include file="common:footer" /}