<?php use app\base\model\Summary;

$menuAll = true; ?>
{include file="common:admin_header" /}
<style type="text/css">
    .home-head .head-img {
        height: 60px;
    }
</style>
<section class="zyw-container">
    <div class="home-head white-bgcolor clearfix">
        <div class="head-img">
            <div class="head-logo"><img src="__STATIC__/home/img/mylogo.png" alt=""></div>
            <div class="head-name">抓耗子的猫</div>
            <div class="head-icon">
                <a href="<?php echo sfurl('/') ?>"><img src="__STATIC__/home/img/svg/home.svg" height="24" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-cog.svg" alt=""></a>
                <a href=""><img src="__STATIC__/home/img/svg/home-message.svg" alt=""></a>
            </div>
        </div>
        <div class="head-cont">
            <div class="weui-flex">
                <div class="weui-flex__item"><a href="#"><p><?php echo Summary::instance()->getTodayIndent() ?></p><span>今日有效单</span></a></div>
                <div class="weui-flex__item"><a href="#"><p><?php echo Summary::instance()->getTodayGroup() ?></p><span>今日新建团体</span></a></div>
                <div class="weui-flex__item"><a href="#"><p><?php echo Summary::instance()->getTodayAccount() ?></p><span>今日新增会员</span></a></div>
            </div>
        </div>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="<?php echo sfurl('/admin/item/indent/order') ?>">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-1.svg" alt=""> 外卖订单</p>
            </div>
            <div class="weui-cell__ft choose-des">
                管理外卖订单
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625">
        <a href="<?php echo sfurl('/admin/indent/order/status/W') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfh.svg" alt="">
            </div>
            <p class="weui-flex__label">待配餐</p>
        </a>
        <a href="<?php echo sfurl('/admin/indent/order/status/P') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dsh.svg" alt="">
            </div>
            <p class="weui-flex__label">待收货</p>
        </a>
        <a href="<?php echo sfurl('/admin/indent/order/status/C') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dpj.svg" alt="">
            </div>
            <p class="weui-flex__label">已完成</p>
        </a>
    </div>
    <div class="home-cont weui-cells mt-625">
        <a class="weui-cell weui-cell_access" href="#">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="img/svg/home-1.svg" alt=""> 其他功能</p>
            </div>
        </a>
    </div>
    <div class="weui-flex home-order white-bgcolor mb-625" style="margin-bottom: 0">
        <a href="order.html" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">店铺管理</p>
        </a>
        <a href="<?php echo sfurl('/admin/ad') ?>" class="weui-flex__item">
            <div class="weui-flex__icon">
                <img src="__STATIC__/home/img/svg/home-dfk.svg" alt="">
            </div>
            <p class="weui-flex__label">广告管理</p>
        </a>
    </div>
    <div class="home-cont weui-cells mb-625">
        <a class="weui-cell weui-cell_access" href="javascript:;" onclick="alert('感谢您点赞')">
            <div class="weui-cell__bd">
                <p class="choose-text"><img src="__STATIC__/home/img/svg/home-3.svg" alt=""> 支持系统</p>
            </div>
            <div class="weui-cell__ft choose-des">
            </div>
        </a>
    </div>
</section>
{include file="common:footer" /}